camera_topics:
  front:
    image_topic: "/zed2/zed_node/rgb/image_rect_color"
    info_topic: "/zed2/zed_node/rgb/camera_info"
    use_for_training: true
    publish_confidence: true
    publish_input_image: true
    scheduler_weight: 1
  # rear:
  #   image_topic: "/zed2/zed_node/rgb/image_rect_color"
  #   info_topic: "/zed2/zed_node/rgb/camera_info"
  #   use_for_training: true
  #   publish_confidence: true
  #   publish_input_image: true
  #   scheduler_weight: 1
  
# Provides 1080 (height) x 1920 (width) images
network_input_image_height: 184 # 448
network_input_image_width: 336 # 448
